# Generated by Django 4.2.11 on 2024-04-16 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bismi_allah_blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bismi_allah_blogs',
            old_name='user_id',
            new_name='user',
        ),
    ]
